# This is a basic workflow to help you get started with Actions

name: MCA Deployment

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      instance:
        type: choice
        description: Which instances would you like to deploy to
        options:
          - Beta
          - Production
          - Seychelles
          - Test
          - All

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, x64, homestead]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: build mercury
        run: |
          rm -rf ../build
          mkdir ../build
          cp -TR . ../build
          tar -cvf build.tar ../build/

      - name: Copy to server
        run: scp build.tar ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOSTNAME }}:${{ secrets.WORKING_DIRECTORY }}

      - name: ssh and unpack
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            cd '${{ secrets.WORKING_DIRECTORY }}'
            tar -xzvf build.tar
            # depending on the instance input we want to do different stuff here
