# This is a basic workflow to help you get started with Actions

name: MCA Deployment

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      instance:
        type: choice
        description: Which instances would you like to deploy to
        options:
          - Beta
          - Production
          - Seychelles
          - Test
          - All

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, x64, homestead]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: build mercury
        run: |
          rm -rf ../build
          mkdir ../build
          cp -TR . ../build
          tar -cvf build.tar ../build/

      - name: Copy to server
        run: scp -P 3003 build.tar ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOSTNAME }}:~/test/

      - name: ssh and unpack
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            cd /home/agoodlet/test/
            # if we already have an unpacked build we want to get rid of it
            # perhaps we should be mv ./build ./build_old instead
            if [ -d ./build.tar ]; then rm -rf /home/agoodlet/test/build.tar; fi
            if [ -d ./build ]; then rm -rf /home/agoodlet/test/build; fi
            # unpack build
            tar xvf build.tar
            # depending on the instance input we want to do different stuff here
            command="/root/create_or_update_mca_instance.php -m update"
            instance="${{ github.event.inputs.instance }}"
            # surely there's something we can do to make this easier to maintain
            case "$instance" in
              # if instance = all we dont' need to filter
              "All")
                ;;
              # if instance = production -u prod,users
              "Production")
                command="$command -u ${{ vars.PROD_USERS }}";;
              # if instance = beta -e prod,users
              "Beta")
                command="$command -e ${{ vars.PROD_USERS }}";;
              # if instance = seychelles -u seychelles
              "Seychelles")
                command="$command -u scmercurybilling";;
              # if instance = test -u dveale,demomercury,agoodlet
              "Test")
                command="$command -u dveale,demomercury,agoodlet";;
            esac
            echo $command
