name: MCA Deployment FE

on:
  workflow_dispatch:
    inputs:
      instance:
        type: choice
        description: Which instances would you like to deploy to
        options:
          - Beta
          - Production
          - Seychelles
          - Test
          - All

jobs:
  build:
    runs-on: [self-hosted, linux, x64, homestead]

    steps:
      - uses: actions/checkout@v2

      - name: build mercury
        run: |
          rm -rf ../build
          mkdir ../build
          cp -TR . ../build
          tar -cvf build.tar ../build/

      - name: Copy to server
        run: scp -P 3003 build.tar ${{ secrets.MCA_SSH_USERNAME }}@${{ secrets.MCA_SSH_HOSTNAME }}:${{ secrets.MCA_WORKING_DIRECTORY }}/Core/public

      - name: ssh and unpack
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.MCA_SSH_HOSTNAME }}
          username: ${{ secrets.MCA_SSH_USERNAME }}
          key: ${{ secrets.MCA_SSH_PRIVATE_KEY }}
          port: ${{ secrets.MCA_SSH_PORT }}
          script: |
            set -e
            cd '${{ secrets.MCA_WORKING_DIRECTORY }}/Core/public'
            # unpack
            if [ -d ./build ]; then rm -rf '${{ secrets.MCA_WORKING_DIRECTORY }}/Core/public/build/'; fi
            tar xvf build.tar
            # take the content out of build and into the public folder
            # using -f flag to make sure we overwrite anything in the destination
            cp -rf ./build/* .

            # depending on the instance input we want to do different stuff here
            command="/root/create_or_update_mca_instance.php -m update"
            instance="${{ github.event.inputs.instance }}"

            # get users from their groups
            production_users="$(getent group production | awk -F ':' '{print $4}')"
            test_users="$(getent group test | awk -F ':' '{print $4}')"

            case "$instance" in
              # if instance = all we dont' need to filter
              "All")
                ;;
              # if instance = production -u prod_users
              "Production")
                command="$command -u $production_users";;
              # if instance = beta -e prod_users
              "Beta")
                command="$command -e $production_users";;
              # if instance = seychelles -u seychelles
              "Seychelles")
                command="$command -u scmercurybilling";;
              # if instance = test -u dveale,demomercury,agoodlet
              "Test")
                command="$command -u $test_users";;
            esac

            # execute the command
            # eval "$command"
            echo "$command"
